export interface File {
  id: string;
  name: string;
  type: "file";
  url: string;
  parent: string;
  size: string;
}

export type Folder = {
  id: string;
  name: string;
  type: "folder";
  parent: string | null;
};


export const mockFolders: Folder[] = [
  { id: "root", name: "root", type: "folder", parent: null },
  { id: "1", name: "Documents", type: "folder", parent: "root" },
  { id: "2", name: "Images", type: "folder", parent: "root" },
  { id: "3", name: "Work", type: "folder", parent: "root" },
  { id: "4", name: "Presentations", type: "folder", parent: "3" },
];




export const mockFiles: File[] = [
  {
    id: "4",
    name: "Resume.pdf",
    type: "file",
    url: "/files/resume.pdf",
    parent: "root",
    size: "1.2 MB",
  },
  {
    id: "5",
    name: "Project Proposal.docx",
    type: "file",
    url: "/files/proposal.docx",
    parent: "1",
    size: "2.5 MB",
  },
  {
    id: "6",
    name: "Vacation.jpg",
    type: "file",
    url: "/files/vacation.jpg",
    parent: "2",
    size: "3.7 MB",
  },
  {
    id: "7",
    name: "Profile Picture.png",
    type: "file",
    url: "/files/profile.png",
    parent: "2",
    size: "1.8 MB",
  },
  {
    id: "9",
    name: "Q4 Report.pptx",
    type: "file",
    url: "/files/q4-report.pptx",
    parent: "8",
    size: "5.2 MB",
  },
  {
    id: "10",
    name: "Budget.xlsx",
    type: "file",
    url: "/files/budget.xlsx",
    parent: "3",
    size: "1.5 MB",
  },
];



export const mockNotes = [
  {
    id: 1,
    ownerId: "user_01",
    title: "Meeting Notes",
    content: "Discussed quarterly goals and project milestones.",
    excerpt: "Quarterly goals and milestones covered.",
    category: "Work",
    tags: ["meeting", "q1", "milestones"],
    color: "blue",
    isPinned: true,
    isStarred: true,
    priority: "high" as const,
    status: "completed" as const,
    isBookmarked: false,
    createdAt: new Date("2025-05-01T10:00:00Z"),
    updatedAt: new Date("2025-05-01T12:00:00Z"),
    author: "John Doe",
    wordCount: 250,
    readingTime: 2,
    template: "meeting",
    linkedNotes: [2, 3],
    attachments: ["launch_checklist.pdf"],
    collaborators: ["user_02"],
    aiGenerated: false,
    aiSummary: "Covers project goals and timeline.",
    version: 1,
    isShared: true,
    viewCount: 25,
    folder: "Projects/2025"
  },
  {
    id: 2,
    ownerId: "user_01",
    title: "Product Launch Plan",
    content: "Step-by-step plan for the new product launch.",
    excerpt: "Timeline and tasks for product launch.",
    category: "Planning",
    tags: ["launch", "product", "timeline"],
    color: "green",
    isPinned: false,
    isStarred: true,
    isBookmarked: true,
    createdAt: new Date("2025-04-15T09:00:00Z"),
    updatedAt: new Date("2025-04-16T11:30:00Z"),
    author: "John Doe",
    wordCount: 1200,
    priority: "high" as const,
    status: "completed" as const,
    readingTime: 8,
    template: "project-plan",
    linkedNotes: [1],
    attachments: ["launch_checklist.pdf"],
    collaborators: ["user_03"],
    aiGenerated: true,
    aiSummary: "Launch strategy with tasks and resources.",
    version: 2,
    isShared: true,
    viewCount: 80,
    folder: "Marketing/Launches"
  },
  {
    id: 3,
    ownerId: "user_01",
    title: "Personal Reflection",
    content: "Reflecting on the challenges and growth over the past month.",
    excerpt: "Monthly reflections and self-assessment.",
    category: "Personal",
    tags: ["reflection", "journal", "growth"],
    color: "purple",
    isPinned: false,
    isStarred: false,
    isBookmarked: true,
    createdAt: new Date("2025-06-01T20:00:00Z"),
    updatedAt: new Date("2025-06-01T20:00:00Z"),
    author: "John Doe",
    wordCount: 800,
    readingTime: 5,
    priority: "high" as const,
    status: "completed" as const,
    template: "journal",
    linkedNotes: [],
    attachments: [],
    collaborators: [],
    aiGenerated: false,
    aiSummary: "Insights and emotions from last month.",
    version: 1,
    isShared: false,
    viewCount: 10,
    folder: "Personal/Journal"
  },
]


export const mockCalendarEvents = [
  {
    id: 1,
    ownerId: "user_01",
    title: "Team Sync",
    description: "Weekly team sync-up on project status.",
    date: "2025-06-19",
    startTime: "10:00",
    endTime: "11:00",
    type: "meeting",
    priority: "medium",
    location: "Zoom",
    fileLinks: ["https://link.to/agenda"],
    recurring: "weekly",
    reminderMinutes: 15,
    completed: false,
    createdAt: new Date("2025-06-10T09:00:00Z")
  },
  {
    id: 2,
    ownerId: "user_01",
    title: "Doctor Appointment",
    description: "Annual health checkup.",
    date: "2025-06-20",
    startTime: "14:00",
    endTime: "15:00",
    type: "personal",
    priority: "high",
    location: "City Clinic",
    fileLinks: ["https://link.to/agenda"],
    recurring: "yearly",
    reminderMinutes: 60,
    completed: false,
    createdAt: new Date("2025-06-12T13:00:00Z")
  },
  {
    id: 3,
    ownerId: "user_02",
    title: "Marketing Review",
    description: "Review the latest marketing campaign performance.",
    date: "2025-06-21",
    startTime: "09:00",
    endTime: "10:30",
    type: "work",
    priority: "high",
    location: "Office Room 3A",
    fileLinks: ["https://link.to/report.pdf"],
    recurring: "none",
    reminderMinutes: 30,
    completed: false,
    createdAt: new Date("2025-06-13T08:00:00Z")
  },
  {
    id: 4,
    ownerId: "user_01",
    title: "Yoga Class",
    description: "Weekly yoga session for relaxation.",
    date: "2025-06-22",
    startTime: "18:00",
    endTime: "19:00",
    type: "personal",
    priority: "low",
    location: "Community Center",
    fileLinks: ["https://link.to/agenda"],
    recurring: "weekly",
    reminderMinutes: 10,
    completed: false,
    createdAt: new Date("2025-06-14T07:30:00Z")
  },
  {
    id: 5,
    ownerId: "user_03",
    title: "Client Call",
    description: "Quarterly check-in with ACME Corp.",
    date: "2025-06-24",
    startTime: "16:00",
    endTime: "17:00",
    type: "call",
    priority: "medium",
    location: "Google Meet",
    fileLinks: ["https://link.to/agenda"],
    recurring: "quarterly",
    reminderMinutes: 20,
    completed: false,
    createdAt: new Date("2025-06-15T11:45:00Z")
  },
] as const;





export const mockSettings = {
  id: 1,
  userId: "user_12345",
  name: "Jane Doe",
  email: "jane.doe@example.com",
  phone: "+1234567890",
  bio: "Computer Science student passionate about AI and education.",
  institution: "OpenAI University",
  major: "Computer Science",
  graduationYear: "2026",
  location: "San Francisco, CA",
  timezone: "America/Los_Angeles",
  avatar: "https://example.com/avatar.jpg",
  theme: "dark",
  accentColor: "#4F46E5",
  fontSize: "medium",
  compactMode: false,
  animations: true,
  sidebarCollapsed: false,
  showAvatars: true,
  colorBlindMode: false,
  emailNotifications: true,
  pushNotifications: true,
  desktopNotifications: false,
  studyReminders: true,
  deadlineAlerts: true,
  collaborationUpdates: true,
  weeklyDigest: true,
  marketingEmails: false,
  soundEnabled: true,
  vibrationEnabled: true,
  quietHours: {
    enabled: true,
    start: "22:00",
    end: "07:00"
  },
  profileVisibility: "friends",
  showOnlineStatus: true,
  allowDirectMessages: true,
  shareStudyStats: false,
  dataCollection: true,
  analyticsOptIn: true,
  twoFactorAuth: false,
  sessionTimeout: 30,
  aiAssistantEnabled: true,
  autoSuggestions: true,
  smartNotifications: true,
  learningAnalytics: true,
  personalizedContent: true,
  voiceInteraction: false,
  creativityLevel: 80,
  responseLength: "medium",
  preferredLanguage: "en",
  contextAwareness: true,
  defaultStudyDuration: 25,
  breakDuration: 5,
  longBreakInterval: 4,
  focusMode: true,
  backgroundSounds: false,
  pomodoroEnabled: true,
  goalTracking: true,
  progressSharing: false,
  studyStreaks: true,
  difficultyAdaptation: true,
  spacedRepetition: true,
  createdAt: new Date()
}


export const mockDocuments = [
  {
    id: "1718793000010",
    name: "Intro to Algebra",
    type: "pdf",
    size: 2450,
    dateCreated: new Date("2024-08-10T10:30:00Z"),
    dateModified: new Date("2024-08-12T14:45:00Z"),
    tags: ["math", "algebra", "basics"],
    category: "Math",
    isStarred: true,
    isShared: false,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=Algebra",
    description: "Basic introduction to algebraic concepts and equations.",
    author: "user_12345",
    version: 1,
    downloadCount: 43,
    viewCount: 198,
    aiProcessed: true,
    aiSummary: "Covers variables, expressions, and simple equations.",
    aiTags: ["math", "variables", "expressions"],
    collaborators: [],
    parentFolder: "math_notes",
    path: "/documents/math/intro-to-algebra",
    status: "synced",
    aiScore: 85.5,
    readingTime: 12,
    difficulty: "beginner",
    subject: "Algebra"
  },
  {
    id: "1718793000020",
    name: "Photosynthesis Explained",
    type: "docx",
    size: 3150,
    dateCreated: new Date("2024-07-15T09:00:00Z"),
    dateModified: new Date("2024-07-16T11:15:00Z"),
    tags: ["biology", "plants", "photosynthesis"],
    category: "Science",
    isStarred: false,
    isShared: true,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=Bio",
    description: "Detailed notes on the photosynthesis process in plants.",
    author: "user_12345",
    version: 1,
    downloadCount: 76,
    viewCount: 265,
    aiProcessed: true,
    aiSummary: "Explains the light and dark reactions of photosynthesis.",
    aiTags: ["biology", "light reactions", "chlorophyll"],
    collaborators: ["user_23456"],
    parentFolder: "science_notes",
    path: "/documents/science/photosynthesis",
    status: "synced",
    aiScore: 91.3,
    readingTime: 15,
    difficulty: "intermediate",
    subject: "Biology"
  },
  {
    id: "1718793000030",
    name: "Shakespearean Literature Overview",
    type: "pdf",
    size: 1800,
    dateCreated: new Date("2024-05-21T16:20:00Z"),
    dateModified: new Date("2024-05-22T17:00:00Z"),
    tags: ["literature", "shakespeare", "english"],
    category: "Literature",
    isStarred: false,
    isShared: false,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=Lit",
    description: "A summary of major Shakespeare works and themes.",
    author: "user_12345",
    version: 1,
    downloadCount: 34,
    viewCount: 120,
    aiProcessed: false,
    aiSummary: null,
    aiTags: [],
    collaborators: [],
    parentFolder: "english",
    path: "/documents/literature/shakespeare-overview",
    status: "synced",
    aiScore: null,
    readingTime: 10,
    difficulty: "intermediate",
    subject: "English"
  },
  {
    id: "1718793000040",
    name: "World War II Timeline",
    type: "pptx",
    size: 4250,
    dateCreated: new Date("2024-06-01T10:00:00Z"),
    dateModified: new Date("2024-06-05T10:00:00Z"),
    tags: ["history", "ww2", "timeline"],
    category: "History",
    isStarred: true,
    isShared: true,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=WW2",
    description: "Chronological presentation of WWII key events.",
    author: "user_12345",
    version: 1,
    downloadCount: 98,
    viewCount: 340,
    aiProcessed: true,
    aiSummary: "Timeline covering causes, battles, and aftermath.",
    aiTags: ["history", "ww2", "events"],
    collaborators: ["user_45678"],
    parentFolder: "history",
    path: "/documents/history/ww2-timeline",
    status: "synced",
    aiScore: 89.1,
    readingTime: 20,
    difficulty: "advanced",
    subject: "World History"
  },
  {
    id: "1718793000050",
    name: "Calculus Cheat Sheet",
    type: "pdf",
    size: 1520,
    dateCreated: new Date("2024-08-01T08:30:00Z"),
    dateModified: new Date("2024-08-01T08:45:00Z"),
    tags: ["math", "calculus", "cheat-sheet"],
    category: "Math",
    isStarred: false,
    isShared: false,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=Calc",
    description: "Quick reference for calculus formulas and rules.",
    author: "user_12345",
    version: 1,
    downloadCount: 112,
    viewCount: 410,
    aiProcessed: true,
    aiSummary: "Key formulas for derivatives and integrals.",
    aiTags: ["math", "formulas", "reference"],
    collaborators: [],
    parentFolder: "math_notes",
    path: "/documents/math/calculus-cheat-sheet",
    status: "synced",
    aiScore: 88.7,
    readingTime: 6,
    difficulty: "intermediate",
    subject: "Calculus"
  },
  {
    id: "1718793000060",
    name: "Cell Structure Comparison",
    type: "docx",
    size: 2900,
    dateCreated: new Date("2024-04-20T13:00:00Z"),
    dateModified: new Date("2024-04-21T14:00:00Z"),
    tags: ["biology", "cells", "comparison"],
    category: "Science",
    isStarred: false,
    isShared: false,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=Cells",
    description: "Differences between plant and animal cells.",
    author: "user_12345",
    version: 1,
    downloadCount: 50,
    viewCount: 185,
    aiProcessed: false,
    aiSummary: null,
    aiTags: [],
    collaborators: [],
    parentFolder: "science_notes",
    path: "/documents/science/cell-structure",
    status: "synced",
    aiScore: null,
    readingTime: 11,
    difficulty: "beginner",
    subject: "Biology"
  },
  {
    id: "1718793000070",
    name: "Modern Poetry Analysis",
    type: "pdf",
    size: 2100,
    dateCreated: new Date("2024-03-12T11:00:00Z"),
    dateModified: new Date("2024-03-12T12:30:00Z"),
    tags: ["poetry", "modernism", "analysis"],
    category: "Literature",
    isStarred: true,
    isShared: false,
    isLocked: true,
    thumbnail: "https://placehold.co/100x100?text=Poetry",
    description: "Analytical breakdown of modernist poetry themes.",
    author: "user_12345",
    version: 1,
    downloadCount: 62,
    viewCount: 145,
    aiProcessed: true,
    aiSummary: "Focuses on style, symbolism, and social context.",
    aiTags: ["poetry", "analysis", "themes"],
    collaborators: [],
    parentFolder: "english",
    path: "/documents/literature/modern-poetry",
    status: "synced",
    aiScore: 82.4,
    readingTime: 9,
    difficulty: "advanced",
    subject: "English"
  },
  {
    id: "1718793000080",
    name: "Cold War Key Facts",
    type: "docx",
    size: 3300,
    dateCreated: new Date("2024-02-10T15:00:00Z"),
    dateModified: new Date("2024-02-11T10:00:00Z"),
    tags: ["history", "cold war", "usa", "ussr"],
    category: "History",
    isStarred: false,
    isShared: false,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=ColdWar",
    description: "Essential information and figures from the Cold War era.",
    author: "user_12345",
    version: 1,
    downloadCount: 58,
    viewCount: 200,
    aiProcessed: false,
    aiSummary: null,
    aiTags: [],
    collaborators: [],
    parentFolder: "history",
    path: "/documents/history/cold-war-facts",
    status: "synced",
    aiScore: null,
    readingTime: 14,
    difficulty: "intermediate",
    subject: "World History"
  },
  {
    id: "1718793000090",
    name: "Statistics Formulas",
    type: "pdf",
    size: 1400,
    dateCreated: new Date("2024-01-05T08:00:00Z"),
    dateModified: new Date("2024-01-06T09:00:00Z"),
    tags: ["statistics", "math", "formulas"],
    category: "Math",
    isStarred: false,
    isShared: true,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=Stats",
    description: "Formulas and definitions for key statistical methods.",
    author: "user_12345",
    version: 1,
    downloadCount: 87,
    viewCount: 320,
    aiProcessed: true,
    aiSummary: "Includes mean, median, standard deviation, and more.",
    aiTags: ["statistics", "definitions", "calculations"],
    collaborators: ["user_78901"],
    parentFolder: "math_notes",
    path: "/documents/math/statistics-formulas",
    status: "synced",
    aiScore: 90.2,
    readingTime: 7,
    difficulty: "intermediate",
    subject: "Statistics"
  },
  {
    id: "1718793000100",
    name: "Genetics Study Guide",
    type: "docx",
    size: 3700,
    dateCreated: new Date("2024-09-01T09:00:00Z"),
    dateModified: new Date("2024-09-01T12:00:00Z"),
    tags: ["genetics", "biology", "study guide"],
    category: "Science",
    isStarred: true,
    isShared: false,
    isLocked: false,
    thumbnail: "https://placehold.co/100x100?text=Genetics",
    description: "In-depth study guide on Mendelian and molecular genetics.",
    author: "user_12345",
    version: 1,
    downloadCount: 120,
    viewCount: 350,
    aiProcessed: true,
    aiSummary: "Outlines inheritance patterns, DNA structure, and mutations.",
    aiTags: ["genetics", "DNA", "inheritance"],
    collaborators: [],
    parentFolder: "science_notes",
    path: "/documents/science/genetics-guide",
    status: "synced",
    aiScore: 93.8,
    readingTime: 18,
    difficulty: "advanced",
    subject: "Biology"
  }
];
